### ISSUE TITLE
Agregar Lista para Agregar Naturalidad de Persona en RIF

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#10]
**Información acerca de la nueva funcionalidad o característica**

Agregar Lista para Agregar Naturalidad de Persona en RIF

**Comment by jesusalbujas** [comment]
![image](https://github.com/user-attachments/assets/24ddbe21-a78a-42f2-9d7d-7205c8547a1f)

![rif](https://github.com/user-attachments/assets/89278456-df8e-44e9-ad89-cda266e48ad3)

**Comment by Zunigaj1101** [comment]
Se probo y si funciona
