### ISSUE TITLE
Columna de Dirección

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#11]
**Información acerca de la nueva funcionalidad o característica**
No deja colocar numero en el campo direccion de la ventana proveedor

https://github.com/user-attachments/assets/c3275729-8065-4b86-bac5-5828a831ea9e

**Comment by jesusalbujas** [comment]
Agregado en release: https://github.com/jesusalbujas/postgres-university/releases/tag/0.0.5

![image](https://github.com/user-attachments/assets/644d90e2-8a02-433d-99c9-aa7b39a8fbcf)

**Comment by Zunigaj1101** [comment]
Se probo y si funciona
