### ISSUE TITLE
Error al completar Activo Fijo

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#12]
Da error al intentar completar un activo fijo

https://github.com/user-attachments/assets/71a1c1b5-c79a-4ad8-873b-fc1be472b593

**Comment by jesusalbujas** [comment]
Se puede observar que no colocó el producto. ¿Ese activo fijo tiene el producto asociado? @Zunigaj1101

**Comment by jesusalbujas** [comment]
Corregido en release: https://github.com/jesusalbujas/postgres-university/releases/tag/0.0.6

- Se cambio el tipo de dato `Character (1)` a `Character (10)` de la Columna `DocAction` en **Adición de Activo**
- Se agrega fecha por defecto en la columna `En fecha de servicio` en `Activo Fijo`  y `Fecha de Documento` en `Adición de Activo`.
  - El problema es que no se estaba guardando la fecha en activo fijo y la adición de activo valida por dicha fecha.

**Comment by Zunigaj1101** [comment]
Ya registra el activo.
Al darle en `Asset Addition Process` el documento se mantiene en `Borrador` .  Pero aun asi permite hacer entrega
