### ISSUE TITLE
Error de nombre de empleados en entrega de activo

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#13]
los nuevos empleados registrados aparecen como -1

https://github.com/user-attachments/assets/2de760b7-38de-4a0d-834a-c77512dc0959

**Comment by Zunigaj1101** [comment]
Solucionado, albujas da los detalles.
![Screenshot_20240922_194606](https://github.com/user-attachments/assets/c12e8752-bf5f-4322-a518-1daee3adf170)

**Comment by jesusalbujas** [comment]
> Solucionado, albujas da los detalles. ![Screenshot_20240922_194606](https://private-user-images.githubusercontent.com/126214891/369726435-c12e8752-bf5f-4322-a518-1daee3adf170.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTMzNzcsIm5iZiI6MTcyNzA1MzA3NywicGF0aCI6Ii8xMjYyMTQ4OTEvMzY5NzI2NDM1LWMxMmU4NzUyLWJmNWYtNDMyMi1hNTE4LTFkYWVlM2FkZjE3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMDU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjVmZjQxYTYzNTlmNTBiMjU1YjBkNzc3MzY5NWFlZTRlYmQ1MDQyYWJkZGYzNzI0OGU5NDgzY2ZlNDNlZmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3L-QoYFdFSHyKhWx9ObLiEaXna_5Fp14diMe92AmdHU)

El problema es que se estaba usando el campo `Descripción` en el nombre debido a una validación erronea corregida.
