### ISSUE TITLE
Nombre único en proveedor y no en empleado

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#14]
**Descripción del Error**
Al registrar un nombre en proveedor este afecta al nombre en la ventana empleado. Por lo que al registrar un empleado da error. Esto es porque ambas ventanas pertenecen a la misma tabla.

**Comportamiento Esperado**
Que valide el nombre único solo en `Proveedor` y no en `Empleado`

**Comment by Zunigaj1101** [comment]
Se puso a prueba y funciona correctamente
