### ISSUE TITLE
El nombre del campo Cédula deja guardar letras, lo cual no deberia by zuniga

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#15]
**Descripción del Error**
El nombre del campo Cédula deja guardar letras, lo cual no deberia.

https://github.com/user-attachments/assets/77586d78-3d77-465f-a759-2b54d727bb2a

**Comment by jesusalbujas** [comment]
Se agregó validación para que no deje guardar en caso de que se encuentre texto en dicho campo. Al tener letras en el campo y guardar este arrojará un mensaje de error.

**Comment by Zunigaj1101** [comment]
Se puso a prueba y funciona correctamente
