### ISSUE TITLE
Realizar una desplegable para elegir el tipo de identidad donde se muestre V (venezolano) y E (extranjero) 

### ISSUE THREAD

**Issue by GIGIL0VESVT** [jesusalbujas/adempiere-university-project#2]
Desplegar la opción de elegir el tipo de identidad en donde se muestre **V y E**

**Comment by jesusalbujas** [comment]
Agregado en release:

![nacionalidad](https://github.com/user-attachments/assets/fb957d78-e56c-4dda-8a53-c783c88eb92b)

**Comment by Zunigaj1101** [comment]
Se probo y si funciona
