### ISSUE TITLE
Error al completar activo fijo

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#25]
Error al completar activo fijo

https://github.com/user-attachments/assets/f928ffcf-ef48-485c-9017-4bf1fdcb6b49

**Comment by jesusalbujas** [comment]
El error es que se asigno el trigger a dicha tabla. Al hacer esto intenta insertar en un campo value inexistente

**Comment by Zunigaj1101** [comment]
Error solucionado
