### ISSUE TITLE
Error reporte de proveedores

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#28]
Al hacer un reporte de proveedores, no filtra los empleados recien creados

![Error de reporte proveedor](https://github.com/user-attachments/assets/843b2e21-4397-4ce5-b580-efe02a0afbeb)

**Comment by jesusalbujas** [comment]
Corregido en release: [2.0.2](https://github.com/jesusalbujas/postgres-university/releases/tag/2.0.2)

**Comment by Zunigaj1101** [comment]
Se puso a prueba y funciona correctamente
