### ISSUE TITLE
Cambiar el nombre de numero de identificación por cedula de identificación 

### ISSUE THREAD

**Issue by GIGIL0VESVT** [jesusalbujas/adempiere-university-project#3]
Reemplazar en **Numero de identificación** por **Cedula de identificación**

**Comment by Zunigaj1101** [comment]
Aun no se cambia el nombre del campo y deja guardar letras, lo cual no deberia.

https://github.com/user-attachments/assets/289c8fc3-9e7b-49cf-97a8-b058caa07ae2

**Comment by jesusalbujas** [comment]
Corregido en commit: https://github.com/jesusalbujas/postgres-university/commit/27d3cf45d517d5a90260a5f9ff206348a03d4e96
![image](https://github.com/user-attachments/assets/01ecab15-a602-496a-ae47-0e078f2092e5)
