### ISSUE TITLE
Agregar transaccional Desincorporacion

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#30]
**Información acerca de la nueva funcionalidad o característica**
Se necesita agregar la ventana Desincorporacion

**Comment by jesusalbujas** [comment]
Agregado en release 2.0.5: https://github.com/jesusalbujas/adempiere-university-project/issues/30

**Comment by Zunigaj1101** [comment]
Al selecionar `F.Documento `me elimina los demas campos.

https://github.com/user-attachments/assets/37a3b552-31ce-456b-890b-0c8481e75c77

**Comment by Zunigaj1101** [comment]
- A mi parecer el F.Documento esta demas, solo con seleccionar el activo fijo basta.
- El campo `Costo del activo fijo` ya deberia tener el monto que se le agrego en `Completar activo`, si no se esta usando depreciacion, no deberia de cambiar el monto. resulta que `Completar acitvo` no esta registrando el monto en` Valor activo`.

**Comment by jesusalbujas** [comment]
Corregido en release 2.3.0
