### ISSUE TITLE
Cambiar mensaje de error en Proveedor y lógica de validación

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#31]
- Cambiar el mensaje `Error:nombre ya existe` por `Proveedor ya existe en esta empresa`. 

- Para que se cumpla esta condicion se debe agregar una validacion que deje registrar dos proveedores con el mismo nombre pero que pertenezcan a empresas diferentes se puede hacer filtrando por el `Nro de Rif` + `Naturalidad` o El nombre empresa (no es muy practico ya que es mas probable que el usuario coloque mal el nombre que el Rif)

**Comment by jesusalbujas** [comment]
- Se corrige script:  [update: Se corrige lógica para validar que un proveedor no exista en la misma empresa pero si en empresas diferentes](https://github.com/jesusalbujas/adempiere-university-project/commit/eac1267911a11ed44153f9abcf680896b3d7aeb8)

**Comment by jesusalbujas** [comment]
Corregido en release: https://github.com/jesusalbujas/postgres-university/releases/tag/2.0.7

**Comment by Zunigaj1101** [comment]
Funciona correctamente
