### ISSUE TITLE
Inconsistencia Producto - Proveedor

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#32]
**Información acerca de la nueva funcionalidad o característica**
Al registrar un producto se le asigna el proveedor, esta incorrecto.

![Producto - proveedor ](https://github.com/user-attachments/assets/8aa70072-97c4-4ad4-890c-62d11b4948e1)

En este ejemplo se le asigno el Proveedor "Jose" al producto "Laptop", luego al internar crear cualquier activo fijo que parta desde laptop sin importar su marca o modelo, van a tener todas el mismo proveedor.

Por ello, se propone mover los campos de proveedor a la transaccional `Activo Fijo`

**Comment by jesusalbujas** [comment]
1. Se agregó la columna Name2 en la Tabla A_Asset (Activo Fijo) para almacenar el nombre de la empresa.
2. Se agregó la columna Phone en la Tabla A_Asset (Activo Fijo) para almacenar el télefono de la empresa.

- Se retiran los campos de la ventana producto y se agregan en Activo Fijo (junto al script para traer el nombre de la empresa y telefono)
![image](https://github.com/user-attachments/assets/934bd6bd-ed2b-4151-a46c-f992111fc951)


Corregido en release: https://github.com/jesusalbujas/postgres-university/releases/tag/2.0.7

**Comment by Zunigaj1101** [comment]
Funciona Correctamente
