### ISSUE TITLE
Cambios importantes en Activo fijo 

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#33]
**Información acerca de la nueva funcionalidad o característica**
- Al crear un activo fijo debe ser obligatorio que el campo `ubicacion` se mantenga en "Almacen".
- quitar `Fecha creacion` de la ventana `Completar activo` y agregarlo en `Activo fijo`.
- quitar los check `depreciar` y `depreciacion total`.

![Activo fijo - ubicacion](https://github.com/user-attachments/assets/64084c5e-bd33-4e23-b322-3fcc0bd91f64)

**Comment by jesusalbujas** [comment]
- Se agregó lógica por defecto al campo ubicación en Activo Fijo para solo permitir "Almacen".
- Se ocultaron los check depreciar y depreciacion total
- Se ocultó campo `Fecha creacion` de la ventana `Completar activo` y se agregó en `Activo fijo`.

Corregido en release: https://github.com/jesusalbujas/postgres-university/releases/tag/2.0.7

**Comment by Zunigaj1101** [comment]
Funciona correctamente
