### ISSUE TITLE
No aparece opción imprimir en las ventanas

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#34]
**Información acerca de la nueva funcionalidad o característica**
- No aparece para hacer repotes desde la ventanas:
  - Modelo.
  - Proveedor.
  - Marca.
  - Empleado.
  - Ubicacion.
  - Todas las de `Movimiento de activo`.

**Comment by jesusalbujas** [comment]
El problema es que no se habían agregado los reportes a las pestañas de dichas ventanas.

Corregido en release: https://github.com/jesusalbujas/postgres-university/releases/tag/2.0.8
