### ISSUE TITLE
Cambios en completar activo fijo

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#35]
**Información acerca de la nueva funcionalidad o característica**
- Quitar uno de los campos `Monto ingreso` y `Valor del activo` (ver cual es el obligatorio en la bd).
- Quitar` Fecha creacion` de la ventana `Completar activo` y agregarlo en `Activo fijo.`

 ![Completar activo, quitar](https://github.com/user-attachments/assets/ceb7138d-06a5-4a01-ae4b-1e92e660472d)

**Comment by jesusalbujas** [comment]
- Se ocultó campo `Monto ingreso`.
- Se ocultó `Fecha creacion` de la ventana Completar activo y se agregó en Activo fijo.

Corregido en release: https://github.com/jesusalbujas/postgres-university/releases/tag/2.0.7

**Comment by Zunigaj1101** [comment]
Funciona Correctamente
