### ISSUE TITLE
Se requiere agregar parametros en reportes

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#36]
**Información acerca de la nueva funcionalidad o característica**
- Busqueda inteligente para todos los reportes en el menu, para las ventanas dejarlo igual

**Comment by jesusalbujas** [comment]
Se agrega parametro a los reportes Tipo de Producto y Proveedor.

Agregado en Release: https://github.com/jesusalbujas/postgres-university/releases/tag/2.0.8

**Comment by jesusalbujas** [comment]
Se agrega parametros a todos los reportes excepto Marca de Activo y Ubicación 

Agregado en Release: https://github.com/jesusalbujas/postgres-university/releases/tag/2.0.8

**Comment by Zunigaj1101** [comment]
Aparece para ajustar los parametros del reporte en `Modelo activo` pero no se genera el reporte.

https://github.com/user-attachments/assets/e2c94e9e-0e1a-4569-9629-5a84972c75f4

**Comment by Zunigaj1101** [comment]
corregido en release: 2.1.2

Funciona correctamente
