### ISSUE TITLE
Campo "Valor acitvo" de la ventana completar activo

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#37]
**Información acerca de la nueva funcionalidad o característica**
Luego de crear un registro en Completar activo, el campo Valor activo queda en cero.

**Comment by jesusalbujas** [comment]
Se corrige en release 2.1.3

detalle: se cambio el campo monto de entrada por valor del activo

**Comment by Zunigaj1101** [comment]
Funciona correctamente
