### ISSUE TITLE
Activo fijo, Error campo "Proveedores"

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#38]
Al seleccionar el campo `proveedores` no filtra los proveedores de los empleados recien registrados.

![acitvo fijo, error campo proveedores](https://github.com/user-attachments/assets/d30f0d29-7637-470b-adc6-a27b22d3c5ed)

**Comment by jesusalbujas** [comment]
Se corregido en release 2.1.0

Detalle: Se estaba filtrando por proveedor y no se estaba considerando la columna empleado

**Comment by Zunigaj1101** [comment]
Funciona correctamente
