### ISSUE TITLE
El ID de la ventana "Completar Acitvo" no se reinicia.

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#39]
El ID de la ventana "Completar Acitvo" no se reinicia.

![Completar codigo, el id no se reinicio](https://github.com/user-attachments/assets/f474c408-511e-4297-a512-945988a40b8b)

**Comment by jesusalbujas** [comment]
Corregido en release: [2.0.9](https://github.com/jesusalbujas/postgres-university/releases/tag/2.0.9)

Detalle: Se estaba insertando en un campo value inexistente. El campo value en Completar Activo es `DocumentNo` o Número de Documento.

**Comment by Zunigaj1101** [comment]
Funciona correctamente
