### ISSUE TITLE
Error al seleccionar un producto en activos fijos

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#4]
**Descripción del Error**
Al seleccionar un producto en Activo Fijo genera un error SQL.

https://github.com/user-attachments/assets/28004673-0992-4d17-9e24-754a8e3ee171

**Comment by Zunigaj1101** [comment]
Solucionado y si deja guardar registro :p

https://github.com/user-attachments/assets/8c7695e0-c22e-4196-ba2e-c54ebfe6c14b
