### ISSUE TITLE
Error en reportes de ventanas y menú

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#41]
Al generar los reportes en ventana te pide parametros esto está mal, ya que en la ventana al estar posicionado en  ese registro debería imprimirlo.

Por otra parte, los reportes de menú si deben solicitar un filtro por el cual sacar el reporte.

**Comment by jesusalbujas** [comment]
corregido en release 2.1.2

**Comment by Zunigaj1101** [comment]
Funciona correctamente
