### ISSUE TITLE
Tipo de producto se coloca Standard al crear registro.

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#42]
Al crear un registro en producto el tipo de producto se coloca predeterminado en Standard

**Comment by jesusalbujas** [comment]
Corregido en release 2.1.3

Aplicar xml:
[UPDATE_M_PRODUCT_CATEGORY_STANDARD_PRODUCT.zip](https://github.com/user-attachments/files/17294830/UPDATE_M_PRODUCT_CATEGORY_STANDARD_PRODUCT.zip)

**Comment by Zunigaj1101** [comment]
Funciona correctamente
