### ISSUE TITLE
Empleado se guarda por defecto como proveedor

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/adempiere-university-project#43]

**Comment by jesusalbujas** [comment]
Corregido en release 2.1.3:

Aplicar xml:
[UPDATE_CBPARTNER_VENDOR_N_IN_EMPLOYEE.zip](https://github.com/user-attachments/files/17295052/UPDATE_CBPARTNER_VENDOR_N_IN_EMPLOYEE.zip)

**Comment by Zunigaj1101** [comment]
Funciona correctamente
