### ISSUE TITLE
Cambios generales en la ventana Asignación y Devolucion de Activo

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#49]
**Información acerca de la nueva funcionalidad o característica**
- Cambiar el nombre de la Ventana "Entrega" de activo a "Asignacion".
- Dejar esa ventana solo `Asignacion` y quitar devolucion.
- Manejar Hora,  y el responsable de hacer el movimiento.
---
# Ventana devolucion
- Debe manejar quien lo devuelve y el encargado de recibirlo

**Comment by jesusalbujas** [comment]
- [x] Cambiar el nombre de la Ventana "Entrega" de activo a "Asignacion".
- [x] Dejar esa ventana solo Asignacion y quitar devolucion.
- [x] [feat: agregar validación para ocultar criterios de búsqueda en el Smart Browser de Asignación de Activo
 bf-1.1.9](https://github.com/jesusalbujas/frontend-university-project/commit/357555b8eac50349959d7ee935efee7b590a9ab3)
- [x] Manejar Hora, y el responsable de hacer el movimiento. (INCOMPLETO)

**Comment by Zunigaj1101** [comment]
## `Asignacion`
- La hora no se esta tomando correctamente.
- Colocar el responsable como referencia de tabla.
- Al asignar un activo debe cambiar el `estado` en Historico y En la ventana Acitvo fijo.
---
## `Devolucion`
- Devolucion no esta filtrando el empleado asignado al activo.
- Al Devolver un activo debe cambiar el `estado` en Historico y En la ventana Acitvo fijo.

**Comment by jesusalbujas** [comment]
- Se agrega el responsable como un campo tipo lista
![image](https://github.com/user-attachments/assets/f3773265-14e0-4070-a427-c9ad749a38f1)

- [x] La hora se toma del inicio de sesión, el usuario puede modificarla.

**Comment by jesusalbujas** [comment]
- [x] Al asignar o devolver un activo se cambia el estado en histórico de activo.
- [x] Se valida que solo muestre `Activado` en Activo Fijo
- Se reestructura ventana activo fijo. 
  - [x] Ahora modelo y marca están en la parte superior.
 - [x] Se corrige campo tipo fecha en Histórico de Activos.
   -  Se agrega trigger para insertar en la fecha de movimiento la fecha de creación.

**Comment by jesusalbujas** [comment]
Se debe crear otra columna para la fecha de movimiento en Histórico,

**Comment by jesusalbujas** [comment]
- [Se agrega trigger para manejar el proceso en general de devolución y entrega](https://github.com/jesusalbujas/adempiere-university-project/blob/main/customizations/sql/trigger/JAU01_Delivery_Process.sql)
