### ISSUE TITLE
Realizar una tabla en donde se guarde los valores que se cumplen dentro de la empresa

### ISSUE THREAD

**Issue by GIGIL0VESVT** [jesusalbujas/adempiere-university-project#5]
Se debe realizar una tabla en donde se guardaran todos los tipos de valores que se realizan en la empresa.

**Comment by jesusalbujas** [comment]
Se agrega lista con los cargos que cumple cada empleado en E.R.P. Consultores y Asociados.

![cargo-de-empleado](https://github.com/user-attachments/assets/fb75ebca-3c76-4592-9303-c275c31febde)

**Comment by Zunigaj1101** [comment]
Se puso a prueba y funciona correctamente
