### ISSUE TITLE
Crear una nueva ventana de "Devolucion" de activo

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#50]
**Información acerca de la nueva funcionalidad o característica**
- Debe manejar el estatus con el que se esta devolviendo el activo (No va para eso esta la descripcion)
- Debe manejar quien lo devuelve y el encargado de recibirlo

**Comment by jesusalbujas** [comment]
Agregado en release: https://github.com/jesusalbujas/postgres-university/releases/tag/2.2.1
