### ISSUE TITLE
Mover campos de completar activo a Activo fijo

### ISSUE THREAD

**Issue by Zunigaj1101** [jesusalbujas/adempiere-university-project#51]
**Información acerca de la nueva funcionalidad o característica**
- Mover los campos: `moneda`, `Valor`, `Cantidad` a la ventana activo fijo.

**Comment by jesusalbujas** [comment]
Se ha movido los campos `moneda`, `Valor` y `Cantidad` a la ventana activo fijo.
![image](https://github.com/user-attachments/assets/9838caa8-adc6-42d8-8e26-de749950b605)


Release: 2.2.0

**Comment by jesusalbujas** [comment]
Adicionalmente se agregó un validador para no permitir caracteres especiales y dejar el valor y cantidad del activo en cero (0)

**Comment by jesusalbujas** [comment]
https://github.com/jesusalbujas/postgres-university/releases/tag/2.2.0
