### ISSUE TITLE
Reiniciar claves primarias en la Base de Datos

### ISSUE THREAD

**Issue by GIGIL0VESVT** [jesusalbujas/adempiere-university-project#8]
Reiniciar claves primarias en la Base de Datos

**Comment by jesusalbujas** [comment]
Se agregan triggers:
- [feat: Se agrega triggers a todas las tablas para usar el ID desde 1](https://github.com/jesusalbujas/adempiere-university-project/commit/70218310bea7f434206d827c5cd5a33f73d91816)

**Comment by jesusalbujas** [comment]
En las ventanas:

- Marca de Activo no tomó la secuencia

- Modelo de Activo no tomó la secuencia

**Comment by jesusalbujas** [comment]
Corregido en release: https://github.com/jesusalbujas/postgres-university/releases/tag/1.0.0

![image](https://github.com/user-attachments/assets/52a0c602-2511-413b-9b4f-dc208307e202)

**Comment by Zunigaj1101** [comment]
En la ventana `Ubicacion` no se reinicia el ID luego de registrar
![ubicacion no se reinicia el id, ](https://github.com/user-attachments/assets/e5ac376f-52ed-44bf-b364-8d9ff1de73a5)

**Comment by Zunigaj1101** [comment]
corregido
![Ubicacion](https://github.com/user-attachments/assets/939ff107-2ba5-4bbb-a54f-48e62ce03931)
